const { DateTime } = require('luxon')
/*
const toLocalDate = require('./toLocalDate')

const utcDate = new Date()
console.log(utcDate)
console.log(toLocalDate(utcDate))
*/
//const dt = DateTime.fromJSDate(utcDate, { zone: 'Europe/Copenhagen' }).toJSDate()
//const jsDate = dt.toJSDate()

const dt = DateTime.now()
console.log('raw luxon',dt)
console.log('======= from Luxon',dt)
console.log('toString',dt.toString())
console.log('toFormat',dt.toFormat('yyyy-MM-dd HH:mm:ss'))
console.log('toISO',dt.toISO())
console.log('toUTC',dt.toUTC().toISO())
console.log('toLocal',dt.toLocal().toISO())
const jsDate = dt.toJSDate()
console.log('toJSDate',jsDate)
console.log('======== generer Luxon DateTime from JsDate ==========')
console.log('ToDateTime fromJSDate',DateTime.fromJSDate(jsDate))
console.log('======== generer Luxon DateTime from input string ==========')
const input = '2026-04-17 09:50:04'
console.log('ToDateTime',DateTime.fromFormat(input,'yyyy-MM-dd HH:mm:ss'))
console.log('toJSDate',DateTime.fromFormat(input,'yyyy-MM-dd HH:mm:ss').toJSDate())
console.log('========= Luxon DateTime to string ====================')
//det er det samme som ISO
console.log('toString',DateTime.fromFormat(input,'yyyy-MM-dd HH:mm:ss').toString())
console.log('======= JavaScript dato objekt =======')
const dato = new Date()
console.log('Raw date object         ',dato)
console.log('to locale string        ',dato.toLocaleString())
console.log('to locale string da-DK  ',dato.toLocaleString('da-DK'))
console.log('to locale ZULU TID      ',dato.toLocaleString('da-DK', {timeZone: 'UTC'}))
//console.log('to ISO string',dato.toISOString())
