version: '3.8'

services:

  node:
    image: node:bbr
    command: ["npm","start"]
    container_name: backend
    environment:
      PLATFORM: docker
      HOST_ADDRESS:  ${HOST_ADDRESS}
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3300:3300"
    networks:
      default:
        ipv4_address: ${HOST_ADDRESS}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:bbr
    container_name: mongodb
    volumes:
      - mongodata:/data/db
      - ${DEVOPS_DATA}:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      default:
        ipv4_address: ${VGSERVER}

networks:
  default:
    external: true
    name: humle_net
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"

volumes:
  mongodata:
    external: true
