version: '3.8'

services:

  mongodb:
    image: mongo:bbr
    container_name: mongodb
    volumes:
      - mongodata:/data/db
      - ${DEVOPS_MONGODB}:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      default:
        ipv4_address: ${DB_SERVER}

networks:
  default:
    external: true
    name: humle_net
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"

volumes:
  mongodata:
    external: true
