GET http://localhost:3000/authors

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.length === 4,"Response should have returned 4 authors")
     })
  %}

###

GET http://localhost:3000/authors/12

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.mail === 'Gross@mail.com',"Response should have returned Gross@mail.com")
     })
  %}

###
GET http://localhost:3000/authors/jensen

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400")
  var message = '"value" must be a number'
  client.assert(response.body.details[0].message === message,"Response should have returned empty")
     })
  %}

###
POST http://localhost:3000/authors
Content-Type: application/json

{
  "firstname": "Karin",
  "lastname": "Andersen",
  "mail": "karin@example.com"
}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201")
  client.assert(response.body.data.mail === "karin@example.com","Response should have returned 'karin@example.com")
     })
  %}

###
POST http://localhost:3000/authors
Content-Type: application/json

{
  "firstname": "Karin",
  "lastname": "Andersen"
}

> {% client.test("Request should fail du to missing field mail", function() {
  client.assert(response.status === 400, "Response status is not 400")
  var message = '"firstname" missing required peer "mail"'
  client.assert(response.body.details[0].message === message,"Response should have returned 'field required'")
     })

  %}

###
POST http://localhost:3000/authors
Content-Type: application/json

{
  "firstname": "Karin",
  "lastname": "Andersen",
  "mail": "karin@example.com",
  "dummy": "Illegal field"
}

> {% client.test("Should fail due to field not allowed", function () {
  client.assert(response.status === 400, "Response status is not 400")
  var message = '"dummy" is not allowed'
  client.assert(response.body.details[0].message === message, "Response is not  as expected")
     })
  %}


###
PUT http://localhost:3000/authors
Content-Type: application/json

{
  "_id": "5eef84a264ee594e266c8dd3",
  "id": 29,
  "firstname": "Jesse",
  "lastname": "Liberty",
  "mail": "Liberty@example.com"
}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201")
  client.assert(response.body.data.mail === "Liberty@example.com","Response should have returned 'Liberty@example.com'")
     })
  %}

###
PUT http://localhost:3000/authors
Content-Type: application/json

{
  "_id": "5eef84a264ee594e266c8dd3",
  "id": 29,
  "firstname": "Jesse",
  "lastname": "Liberty"
}

> {% client.test("Should fail due to missing field mail", function () {
     client.assert(response.status === 400, "Response status is not 400")
     var message = "\"_id\" missing required peer \"mail\""
     client.assert(response.body.details[0].message === message, "Response is not  as expected")
     })
  %}

###
DELETE http://localhost:3000/authors/29

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.success === "Authors delete function","Response should have returned 'Authors delete function'")
     })
  %}

###
DELETE http://localhost:3000/authors/jensen

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400")
  var message = '"value" must be a number'
  client.assert(response.body.details[0].message === message,"Response should have returned empty")
     })
  %}
