GET http://localhost:3000/orders

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.length === 11,"Response should have returned 11 orders")
     })
  %}

###
GET http://localhost:3000/orders/3

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.paymethod === "Mastercard","Response should have returned Mastercard")
  client.assert(response.body.data.lines.length === 5,"Response should have returned 5 orderlines")
     })
  %}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "orderdate" : "2020-07-01",
  "invoice" : 301,
  "shipby" : "PostNord",
  "paymethod" : "AMEX",
  "user_id" : 18,
  "lines" : [
    {
      "book_id" : 45,
      "numbooks" : 9
    }]
}

> {% client.test("Request executed successfully", function() {
     client.assert(response.status === 201, "Response status is not 201")
     client.global.set('order',response.body.data.order.id)
     client.log('Den nye ordre...', response.body.data.order.id)
  })
  %}

###
DELETE http://localhost:3000/orders/{{ order }}

> {% client.test("Request executed successfully", function() {
     client.assert(response.status === 200, "Response status is not 200")
  })
  %}

###
PUT http://localhost:3000/orders
Content-Type: application/json

{
  "_id" : "5eef84a264ee594e266c8dde",
  "id" : 11,
  "orderdate" : "2014-07-10T00:00:00.000+02:00",
  "shipdate" : "2014-07-14T00:00:00.000+02:00",
  "invoice" : 55,
  "shipby" : "UPS",
  "paydate" : "2014-07-15T00:00:00.000+02:00",
  "paymethod" : "PayPal",
  "invoicedate" : "2014-07-15T00:00:00.000+02:00",
  "user_id" : 27,
  "lines" : [
    {
      "book_id" : 14,
      "numbooks" : 4
    }
  ]
}

> {% client.test("Request executed successfully", function() {
  client.log('status opdatering..', response.status)
     client.assert(response.status === 200, "Response status is not 200")
  })
  %}

###
PUT http://localhost:3000/orders
Content-Type: application/json

{
  "_id" : "5eef84a264ee594e266c8dde",
  "id" : 11,
  "orderdate" : "2014-07-10T00:00:00.000+02:00",
  "shipdate" : "2014-07-14T00:00:00.000+02:00",
  "invoice" : 55,
  "shipby" : "DHL",
  "paymethod" : "Visa",
  "user_id" : 27,
  "lines" : [
    {
      "book_id" : 14,
      "numbooks" : 4
    }
  ]
}
> {% client.test("Request executed successfully", function() {
     client.assert(response.status === 200, "Response status is not 200")
     client.log('status opdatering..', response.status)
  })
  %}
