GET http://localhost:3300/api/customers

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.length === 29,"Response should have returned 29 users")
     })
  %}

###
GET http://localhost:3300/api/customers/21

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  client.assert(response.body.data.mail === "pwjones@anymail.com" ,"Response should have returned ''6 customers")
     })
  %}

###
POST http://localhost:3300/api/customers
Content-Type: application/json

{
  "name": "Kristian Hansen",
  "city": "Horsens",
  "state": "Østjylland",
  "country": "DK",
  "mail": "kristian@example.com"
}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201")
  client.global.set('kristian_id',response.body.data.customer_id)
     })
  %}

### delete again
DELETE http://localhost:3300/api/customers/{{kristian_id}}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  const user_id = client.global.get('kristian_id')
  client.assert(response.body.data.customer_id == user_id,"Response should have been deleted")
     })
  %}

###
POST http://localhost:3300/api/customers
Content-Type: application/json

{
  "name": "Maria Jensen",
  "city": "Svendborg",
  "country": "DK",
  "state": "Fyn",
  "mail": "maria@example.com"
}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201")
  client.global.set('maria_id',response.body.data.customer_id)
     })
  %}

###
DELETE http://localhost:3300/api/customers/{{maria_id}}

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200")
  const user_id = client.global.get('maria_id')
  client.assert(response.body.data.customer_id == user_id,"Response should have been deleted")
     })
  %}

###
PUT http://localhost:3300/api/customers
Content-Type: application/json

{
  "_id": "5eef84a264ee594e266c8e2c",
  "id": 29,
  "name": "Christian Johnson",
  "city": "Swindon",
  "state": "York",
  "country": "UK",
  "mail": "christian@johnson.nu"

}

> {% client.test("Request failed missing repeat_password", function () {
     client.assert(response.status === 200, "Response status is not 200")
     client.assert(response.body.data.customer_id === 29, "Response should be customer 29")
     })
  %}

###
PUT http://localhost:3300/api/customers
Content-Type: application/json

{
  "_id": "5eef84a264ee594e266c8e2c",
  "id": 29,
  "name": "christina masterson",
  "city": "petersburg",
  "country": "USA",
  "state": "pensylvania",
  "mail": "christina@masterson.nu"

}

> {% client.test("Request failed missing repeat_password", function () {
     client.assert(response.status === 200, "Response status is not 200")
     client.assert(response.body.data.customer_id === 29, "Response should be customer 29")
     })
  %}
